DROP INDEX IF EXISTS i1, i2, i3, i4, i5, i6, i7, i8;

CREATE INDEX i1 on USR USING BTREE (userId);
CREATE INDEX i2 on USR USING BTREE (name);
CREATE INDEX i3 on CONNECTION_USR USING BTREE (userId);
CREATE INDEX i4 on CONNECTION_USR USING BTREE (connectionId);
CREATE INDEX i5 on CONNECTION_USR USING BTREE (status);
CREATE INDEX i6 on MESSAGE USING BTREE (receiverId);
CREATE INDEX i7 on MESSAGE USING BTREE (senderId);
CREATE INDEX i8 on MESSAGE USING BTREE (deleteStatus);